version: '3.8'

# Common environment variables
x-default-environment: &default-environment
  RECRUITAIR_DB_USERNAME: recruitair
  RECRUITAIR_DB_PASSWORD: recruitairpass_1234
  RECRUITAIR_DB_HOST: database
  RECRUITAIR_DB_PORT: 5432
  RECRUITAIR_DB_DATABASE: recruitair

services:
  database-migration:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      <<: *default-environment
    depends_on:
      database:
        condition: service_healthy
    command: ["alembic", "upgrade", "head"]

  
  database:
    image: postgres:16
    environment:
      POSTGRES_USER: recruitair
      POSTGRES_PASSWORD: recruitairpass_1234
      POSTGRES_DB: recruitair
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U recruitair -d recruitair"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - edc-db-data:/var/lib/postgresql/data


  extractor-dispatcher:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      <<: *default-environment
      RECRUITAIR_EXTRACTOR_API_BASE_URL: http://mock-api:3100/extractor/
      RECRUITAIR_EXTRACTOR_API_BEARER_TOKEN: mock_api_token
    depends_on:
      database:
        condition: service_healthy
      database-migration:
        condition: service_completed_successfully
    command: ["python", "-m", "recruitair.workers.extractor"]

  evaluator-dispatcher:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      <<: *default-environment
      RECRUITAIR_EVALUATOR_API_BASE_URL: http://mock-api:3100/evaluator/
      RECRUITAIR_EVALUATOR_API_BEARER_TOKEN: mock_api_token
    depends_on:
      database:
        condition: service_healthy
      database-migration:
        condition: service_completed_successfully
    command: ["python", "-m", "recruitair.workers.evaluator"]

  mock-api:
    image: mocksserver/main
    volumes:
      - ./assets/api-mocks:/input

volumes:
  edc-db-data: