name: Build on Tag
run-name: Build Docker Images on Tag

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger the workflow on version tags like v1.0.0
  workflow_dispatch:  # Allow manual triggering of the workflow

permissions:
  contents: read  # Allows the workflow to read the repository contents
  packages: write  # Allows the workflow to push Docker images to GitHub Packages


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: lower-repo
        shell: bash
        run: echo "repository_owner=${GITHUB_REPOSITORY_OWNER,,}" >> "$GITHUB_OUTPUT"

      - name: Build and Push API Image
        uses: docker/build-push-action@v6
        with:
          push: true
          target: api
          tags: |
            ghcr.io/${{ steps.lower-repo.outputs.repository_owner }}/recruitair/dispatcher-api:${{ github.ref_name }}
            ghcr.io/${{ steps.lower-repo.outputs.repository_owner }}/recruitair/dispatcher-api:latest
          cache-from: type=registry,ref=ghcr.io/${{ steps.lower-repo.outputs.repository_owner }}/recruitair/dispatcher-api:${{ github.ref_name }}
          cache-to: type=inline

      - name: Build and Push Extractor Worker Image
        uses: docker/build-push-action@v6
        with:
          push: true
          target: extractor-worker
          tags: |
            ghcr.io/${{ steps.lower-repo.outputs.repository_owner }}/recruitair/dispatcher-extractor:${{ github.ref_name }}
            ghcr.io/${{ steps.lower-repo.outputs.repository_owner }}/recruitair/dispatcher-extractor:latest
          cache-from: type=registry,ref=ghcr.io/${{ steps.lower-repo.outputs.repository_owner }}/recruitair/dispatcher-extractor:${{ github.ref_name }}
          cache-to: type=inline

      - name: Build and Push Evaluator Worker Image
        uses: docker/build-push-action@v6
        with:
          push: true
          target: evaluator-worker
          tags: |
            ghcr.io/${{ steps.lower-repo.outputs.repository_owner }}/recruitair/dispatcher-evaluator:${{ github.ref_name }}
            ghcr.io/${{ steps.lower-repo.outputs.repository_owner }}/recruitair/dispatcher-evaluator:latest
          cache-from: type=registry,ref=ghcr.io/${{ steps.lower-repo.outputs.repository_owner }}/recruitair/dispatcher-evaluator:${{ github.ref_name }}
          cache-to: type=inline

      - name: Build and Push Database Migration Image
        uses: docker/build-push-action@v6
        with:
          push: true
          target: migration
          tags: |
            ghcr.io/${{ steps.lower-repo.outputs.repository_owner }}/recruitair/dispatcher-migration:${{ github.ref_name }}
            ghcr.io/${{ steps.lower-repo.outputs.repository_owner }}/recruitair/dispatcher-migration:latest
          cache-from: type=registry,ref=ghcr.io/${{ steps.lower-repo.outputs.repository_owner }}/recruitair/dispatcher-migration:${{ github.ref_name }}
          cache-to: type=inline