name: Test on Push
run-name: Run tests on push

on:
  push:
  workflow_dispatch:  # Allow manual triggering of the workflow


jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install dependencies
        run: uv sync --locked --all-extras --dev

      - name: Run tests
        run: uv run pytest tests/
      
  test-build:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - id: lower-repo
        shell: bash
        run: echo "repository_owner=${GITHUB_REPOSITORY_OWNER,,}" >> "$GITHUB_OUTPUT"

      - name: Build API Image
        uses: docker/build-push-action@v6
        with:
          push: false
          target: api
          cache-from: type=registry,ref=ghcr.io/${{ steps.lower-repo.outputs.repository_owner }}/recruitair/dispatcher-api:${{ steps.remove-v.outputs.tag }}
          cache-to: type=inline

      - name: Build Extractor Worker Image
        uses: docker/build-push-action@v6
        with:
          push: false
          target: extractor-worker
          cache-from: type=registry,ref=ghcr.io/${{ steps.lower-repo.outputs.repository_owner }}/recruitair/dispatcher-extractor:${{ steps.remove-v.outputs.tag }}
          cache-to: type=inline

      - name: Build Evaluator Worker Image
        uses: docker/build-push-action@v6
        with:
          push: false
          target: evaluator-worker
          cache-from: type=registry,ref=ghcr.io/${{ steps.lower-repo.outputs.repository_owner }}/recruitair/dispatcher-evaluator:${{ steps.remove-v.outputs.tag }}
          cache-to: type=inline

      - name: Build Database Migration Image
        uses: docker/build-push-action@v6
        with:
          push: false
          target: migration
          cache-from: type=registry,ref=ghcr.io/${{ steps.lower-repo.outputs.repository_owner }}/recruitair/dispatcher-migration:${{ steps.remove-v.outputs.tag }}
          cache-to: type=inline